sudo: required
language: java

addons:
  apt:
    packages:
    - libxml2-utils

script: 
  # Check if translation xml is valid
  - xmllint ItalianTranslation_PlanetCoaster.xml --schema PlanetTranslationXS.xsd --noout

