name: Translation Check

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install dependencies
      run: sudo apt install libxml2-utils
    - name: Check translation
      # Check if translation xml is valid
      run: xmllint ItalianTranslation_PlanetCoaster.xml --schema PlanetTranslationXS.xsd --noout
